### ISSUE TITLE
code question

### ISSUE THREAD

**Issue by Obnayuf** [Boyang--Li/TransOptimize#1]
xdd = -ft_cmd .* sin(theta) ./ p.mass + Fxi;%-Fd
zdd = p.g - ft_cmd .* cos(theta) + Fzi;%-Fl;
where is mass parameter? The code doesn't obey Newton's third law of motion，right?

**Comment by Boyang--Li** [comment]
Hello, thanks for your question.  For x direction, 'p.mass' is the mass parameter. For the z direction, the mass is missed in the original code, and I just fixed it by adding it to the code. The code should reflect Equation 1 in the published paper.
